<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ibex.app</groupId>
  <artifactId>prashanth-app</artifactId>
  <version>1.1</version>
	<packaging>war</packaging>

	<properties>
		<junit.version>4.13.1</junit.version>
		<sonar.host.url>http://54.164.90.55:9000/</sonar.host.url>
		<sonar.login>squ_bb2013b0b3f073b72cfce6605ec80dbae51e989d</sonar.login>

	</properties>
	
	<dependencies>

		<dependency>
		    <groupId>junit</groupId>
		    <artifactId>junit</artifactId>
		    <version>4.13.1</version>
		    <scope>test</scope>
		</dependency>

	</dependencies>

	<distributionManagement>
	
	    <repository>
	      <id>nexus</id>
	      <name>Prashanth Releases Nexus Repository</name>
	      <url>http://34.203.193.15:8081/repository/prashanth-releases//</url>
	    </repository>
	    
	    <snapshotRepository>
	      <id>nexus</id>
	      <name>Prashanth Snapshot Nexus Repository </name>
	      <url>http://34.203.193.15:8081/repository/prashanth-snapshot//</url>
	    </snapshotRepository>
	    
	</distributionManagement>
	
	<build>
	    <plugins>
	        <plugin>
	            <artifactId>maven-war-plugin</artifactId>
	            <version>3.5.1</version>
	            <configuration>
	                <failOnMissingWebXml>false</failOnMissingWebXml>
	            </configuration>
	        </plugin>
	    </plugins>
	</build>
	
</project>
