<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ibex.app</groupId>
  <artifactId>prashanth-app</artifactId>
  <version>1.1</version>
	<packaging>war</packaging>

	<properties>
		<junit.version>4.13.1</junit.version>

	</properties>
	
	<dependencies>

		<dependency>
		    <groupId>junit</groupId>
		    <artifactId>junit</artifactId>
		    <version>4.13.1</version>
		    <scope>test</scope>
		</dependency>

	</dependencies>
	
	<build>
	    <plugins>
	        <plugin>
	            <artifactId>maven-war-plugin</artifactId>
	            <version>3.5.1</version>
	            <configuration>
	                <failOnMissingWebXml>false</failOnMissingWebXml>
	            </configuration>
	        </plugin>
	    </plugins>
	</build>
	
</project>
